elasticsearch.hosts: ["http://elasticsearch:9200"]
server.host: 0.0.0.0
server.port: 5601
xpack.encryptedSavedObjects.encryptionKey: "21706550c15c877e6e4d4fbe5c56b90b"
xpack.reporting.encryptionKey: "1be4185aff8b54c7f4a29f77908933ee"
xpack.security.encryptionKey: "113c19756f367ad2481403254f2a89c2"
elasticsearch.serviceAccountToken: "AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS1zZXJ2aWNlLWFjY291bnQ6MnBONVI4bWVSTUNBSVM5N210U2l1Zw"
# elasticsearch.username: "elastic"
# elasticsearch.password: "yourStrongPassword"