http.host: 0.0.0.0
log.level: info
xpack.monitoring.elasticsearch.password: ${xpack.monitoring.elasticsearch.password}
xpack.monitoring.elasticsearch.username: ${xpack.monitoring.elasticsearch.username}
xpack.monitoring.enabled: ${xpack.monitoring.enabled}
